from __future__ import annotations

from typing import Any, Callable

# Build-time metadata

BORINGSSL_VERSION: str
JA4_SPEC_VERSION: str

# Errors

class CoreError(Exception):
    """Single exception type the Rust layer raises.

    The first positional argument is always a short ``kind`` discriminant
    (``"WantRead"``, ``"WantWrite"``, ``"Eof"``, ``"ZeroReturn"``,
    ``"Verification"``, ``"Protocol"``, ``"Io"``). The Python facade
    pattern-matches on ``args[0]`` and re-raises into the public
    ``ssl.SSLError`` hierarchy.

    When ``kind == "Verification"`` an extra attribute ``verify_code``
    (a BoringSSL ``X509_V_ERR_*`` code) is attached to the instance.
    """

    verify_code: int

class MemoryBio:
    def __init__(self) -> None: ...
    @property
    def pending(self) -> int: ...
    @property
    def eof(self) -> bool: ...
    def read(self, __n: int = -1) -> bytes: ...
    def write(self, __data: bytes) -> int: ...
    def write_eof(self) -> None: ...

class Session:
    def to_der(self) -> bytes: ...
    @staticmethod
    def from_der(__data: bytes) -> Session: ...
    def __reduce__(self) -> tuple[Any, Any]: ...

class Fingerprint:
    def __init__(
        self,
        *,
        cipher_suites: list[int] | None = ...,
        extensions_order: list[int] | None = ...,
        supported_groups: list[int] | None = ...,
        key_shares: list[int] | None = ...,
        signature_algorithms: list[int] | None = ...,
        alpn: list[str] | None = ...,
        alps: list[str] | None = ...,
        alps_use_new_codepoint: bool = ...,
        compress_certificate: list[str] | None = ...,
        record_size_limit: int | None = ...,
        grease: bool = ...,
        grease_sigalgs: bool = ...,
        ech: Any | None = ...,
        padding: int | None = ...,
        trust_anchors: bytes | None = ...,
        permute_trust_anchors: bool = ...,
    ) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    def ja3_string(self) -> str: ...
    def ja3_hash(self) -> str: ...
    def ja4_string(self) -> str: ...
    def ja4_hash(self) -> str: ...
    @staticmethod
    def from_capture(__raw: bytes) -> Fingerprint: ...

class Context:
    def __init__(self, __protocol: int = 2) -> None: ...
    def is_server(self) -> bool: ...

    # Verify mode / hostname
    def set_verify_mode(self, __mode: int) -> None: ...
    def verify_mode(self) -> int: ...
    def set_check_hostname(self, __v: bool) -> None: ...
    def check_hostname(self) -> bool: ...
    def verify_flags(self) -> int: ...
    def set_verify_flags(self, __flags: int) -> None: ...

    # Protocol version bounds
    def set_version_bounds(self, __min: int, __max: int) -> None: ...

    # ALPN / cipher selection
    def set_alpn_protocols(self, __protocols: list[str]) -> None: ...
    def set_ciphers(self, __spec: str) -> None: ...
    def set_curves_list(self, __names: str) -> None: ...

    # Trust store
    def load_verify_locations(
        self,
        cafile: str | None = ...,
        capath: str | None = ...,
    ) -> None: ...
    def add_trusted_cert_der(self, __der: bytes) -> None: ...
    def load_default_certs(self, __purpose: int = 0) -> None: ...
    def load_cert_chain(
        self,
        cert_pem: bytes,
        key_pem: bytes | None = ...,
        password: bytes | None = ...,
    ) -> None: ...
    def cert_store_counts(self) -> tuple[int, int]: ...
    def ca_certs_der(self) -> list[bytes]: ...
    def decode_cert_der(self, __der: bytes) -> dict[str, Any] | None: ...

    # Fingerprint
    def set_fingerprint(self, __fp: Fingerprint | None) -> None: ...
    def fingerprint(self) -> Fingerprint | None: ...

    # Session resumption knobs
    def set_session_id_context(self, __ctx_id: bytes) -> None: ...
    def set_num_tickets(self, __n: int) -> None: ...
    def num_tickets(self) -> int: ...

    # Key logging
    def set_keylog_filename(self, __path: str | None) -> None: ...

    # Server-side SNI dispatch
    def set_sni_callback(
        self,
        __callback: Callable[[SniHandshakeView, str | None], int | None] | None,
    ) -> None: ...

    # Encrypted ClientHello (returns a cloned context; peer-specific config)
    def set_ech_configs(self, __ech: bytes | None) -> Context: ...
    def ech_config_list(self) -> bytes | None: ...

    # Wrap a pair of memory BIOs into a live TLS conversation
    def wrap_bio(
        self,
        incoming: MemoryBio,
        outgoing: MemoryBio,
        server_hostname: str | None = ...,
        session: Session | None = ...,
    ) -> Connection: ...

class Connection:
    def do_handshake(self) -> bool: ...
    def read(self, __n: int) -> bytes: ...
    def write(self, __data: bytes) -> int: ...
    def shutdown(self) -> bool: ...
    def selected_alpn(self) -> str | None: ...
    def version(self) -> str | None: ...
    def cipher(self) -> tuple[str, str, int] | None: ...
    def session(self) -> Session | None: ...
    def session_reused(self) -> bool: ...
    def ech_accepted(self) -> bool: ...
    def ech_retry_configs(self) -> bytes | None: ...
    def is_server(self) -> bool: ...
    def peer_sni(self) -> str | None: ...
    def observed_client_fingerprint(self) -> Fingerprint | None: ...
    def peer_chain_der(self) -> list[bytes]: ...
    def peer_cert_info(self) -> dict[str, Any] | None: ...

class SniHandshakeView:
    """Live, scoped view of an in-flight server handshake handed to the
    ``set_sni_callback`` callable. Holds a raw ``SSL*`` that is only
    valid for the duration of the callback - the dispatcher invalidates
    the pointer on return so post-callback use raises ``RuntimeError``
    rather than touching a dangling handle.
    """

    @property
    def server_name(self) -> str | None: ...
    def swap_context(self, __new_ctx: Context) -> None: ...
